version: '3'
services:
  # db:
  #   restart: always
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: sgbsaints
  #     POSTGRES_DB: kiosk
  #   volumes:
  #     - ./src/data:/var/lib/postgresql/data

  web:
    restart: always
    build: ./src
    volumes:
      - ./src:/usr/src/app/
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 kiosk:app
    network_mode: host
    # depends_on:
    #   - db
